services:
  headscale-docker-client:
    image: ghcr.io/pierre-brocas/tailscale-docker-client:latest
    container_name: tailscale-docker-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      TAILSCALE_KEY: <AUTH_KEY>
      TAILSCALE_SERVER_URL: <SERVER_URL}
      TAILSCALE_HOSTNAME: <HOSTNAME}   
    volumes:
      - ./tailscale-client/:/tailscale/
  caddy:
    image: caddy:latest
    network_mode: container:tailscale-docker-client
    depends_on:
      headscale-docker-client:
        condition: service_started
    restart: unless-stopped