services:
  tailscale-docker-client:
    image: tailscale-docker-client
    container_name: tailscale-docker-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      TAILSCALE_KEY: <AUTH_KEY>
      TAILSCALE_SERVER_URL: <SERVER_URL}
      TAILSCALE_HOSTNAME: <HOSTNAME}     
    volumes:
      - ./tailscale-client/:/tailscale/
